// <auto-generated />
using System;
using FourLoveRestaurant.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourLoveRestaurant.Migrations
{
    [DbContext(typeof(ForLoveDBContext))]
    [Migration("20260228180000_CreateAnnouncements")]
    partial class CreateAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Compone", b =>
                {
                    b.Property<int?>("IdIngredients")
                        .HasColumnType("int")
                        .HasColumnName("ID_INGREDIENTS");

                    b.Property<int?>("IdMenuitems")
                        .HasColumnType("int")
                        .HasColumnName("ID_MENUITEMS");

                    b.HasIndex("IdIngredients");

                    b.HasIndex("IdMenuitems");

                    b.ToTable("COMPONE", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Contein", b =>
                {
                    b.Property<int?>("IdMenuitems")
                        .HasColumnType("int")
                        .HasColumnName("ID_MENUITEMS");

                    b.Property<int?>("IdOrders")
                        .HasColumnType("int")
                        .HasColumnName("ID_ORDERS");

                    b.HasIndex("IdMenuitems");

                    b.HasIndex("IdOrders");

                    b.ToTable("CONTEIN", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Employes__3214EC270D019BCD");

                    b.HasIndex(new[] { "Identification" }, "UQ__Employes__724F06FD2492B526")
                        .IsUnique();

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdSuppliers")
                        .HasColumnType("int")
                        .HasColumnName("ID_SUPPLIERS");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PHOTO");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PRICE");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__INGREDIE__3214EC27D80EB9FA");

                    b.HasIndex("IdSuppliers");

                    b.ToTable("INGREDIENTS", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Menuitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Photo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PHOTO");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PRICE");

                    b.HasKey("Id")
                        .HasName("PK__MENUITEM__3214EC27D025C58F");

                    b.ToTable("MENUITEMS", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<int?>("IdTable")
                        .HasColumnType("int")
                        .HasColumnName("ID_TABLE");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<int?>("Number")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER");

                    b.HasKey("Id")
                        .HasName("PK__ORDERS__3214EC2779F9AEDA");

                    b.HasIndex("IdTable");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("ID_ORDER");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<int?>("Number")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER");

                    b.HasKey("Id")
                        .HasName("PK__PAYMENTS__3214EC273A7CA53E");

                    b.HasIndex("IdOrder");

                    b.ToTable("PAYMENTS", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsActve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3214EC2749DB4217");

                    b.HasIndex(new[] { "Name" }, "UQ__Permissi__737584F6A208D9BD")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Rols__3214EC279C790853");

                    b.HasIndex(new[] { "Name" }, "UQ__Rols__737584F6FFB6A7DE")
                        .IsUnique();

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Identification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IDENTIFICATION");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Photo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PHOTO");

                    b.HasKey("Id")
                        .HasName("PK__SUPPLIER__3214EC27FB36D918");

                    b.ToTable("SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("CAPACITY");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("NUMBER");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("STATE");

                    b.HasKey("Id")
                        .HasName("PK__TABLES__3214EC27474C4711");

                    b.ToTable("TABLES", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int")
                        .HasColumnName("ID_Employe");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    b.Property<bool?>("IsActve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC27EF661207");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "IdEmploye" }, "UQ__Users__FF205F4240CB60B3")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RolPermission", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int")
                        .HasColumnName("ID_Permission");

                    b.HasKey("IdRol", "IdPermission")
                        .HasName("PK__Rol_Perm__FDA9FC35676D7EDC");

                    b.HasIndex("IdPermission");

                    b.ToTable("Rol_Permission", (string)null);
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Compone", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Ingredient", "IdIngredientsNavigation")
                        .WithMany()
                        .HasForeignKey("IdIngredients")
                        .HasConstraintName("FK_ID_INGREDIENTS");

                    b.HasOne("FourLoveRestaurant.Models.Menuitem", "IdMenuitemsNavigation")
                        .WithMany()
                        .HasForeignKey("IdMenuitems")
                        .HasConstraintName("FK_ID_MENUITEMS");

                    b.Navigation("IdIngredientsNavigation");

                    b.Navigation("IdMenuitemsNavigation");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Contein", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Menuitem", "IdMenuitemsNavigation")
                        .WithMany()
                        .HasForeignKey("IdMenuitems")
                        .HasConstraintName("FK_ID_MENUITEMS2");

                    b.HasOne("FourLoveRestaurant.Models.Order", "IdOrdersNavigation")
                        .WithMany()
                        .HasForeignKey("IdOrders")
                        .HasConstraintName("FK_ID_ORDERS");

                    b.Navigation("IdMenuitemsNavigation");

                    b.Navigation("IdOrdersNavigation");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Ingredient", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Supplier", "IdSuppliersNavigation")
                        .WithMany("Ingredients")
                        .HasForeignKey("IdSuppliers")
                        .HasConstraintName("FK_IDSUPPLIERS");

                    b.Navigation("IdSuppliersNavigation");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Order", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Table", "IdTableNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdTable")
                        .HasConstraintName("ID_TABLE");

                    b.Navigation("IdTableNavigation");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Payment", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Order", "IdOrderNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK_ID_ORDER");

                    b.Navigation("IdOrderNavigation");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.User", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Employe", "IdEmployeNavigation")
                        .WithOne("User")
                        .HasForeignKey("FourLoveRestaurant.Models.User", "IdEmploye")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Empleados");

                    b.HasOne("FourLoveRestaurant.Models.Rol", "IdRolNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("IdEmployeNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("RolPermission", b =>
                {
                    b.HasOne("FourLoveRestaurant.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Permiso");

                    b.HasOne("FourLoveRestaurant.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_RolPermiso_Rol");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Employe", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Supplier", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FourLoveRestaurant.Models.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
